### ISSUE TITLE
Unequal Gas Payment

### ISSUE THREAD

**Issue by naterush** [gnidan/RareGem#1]
Use a mapping to Boolean to check if guess is really a color - make gas usage higher when initially deploying contract, but more fair gas usage when checking to see if the guess is a color.

**Comment by gnidan** [comment]
Hey @naterush, beat you to it! 
Is this what you mean: https://github.com/gnidan/RareGem/commit/8a2b4be9d984d6114174ff91aa9c8553b1517cae (and subsequent commit where I remove an extra storage var)
